service: feeling-api

plugins:
  - serverless-offline-python
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-2

functions:
  get_feeling:
    handler: src/functions/feeling.get
    events:
      - http:
          path: /feeling/{id}
          method: get
          cors: true

  create_feeling:
    handler: src/functions/feeling.post
    events:
      - http:
          path: /feeling
          method: post
          cors: true

  update_feeling:
    handler: src/functions/feeling.put
    events:
      - http:
          path: /feeling/{id}
          method: put
          cors: true

  delete_feeling:
    handler: src/functions/feeling.delete
    events:
      - http:
          path: /feeling/{id}
          method: delete
          cors: true

  put_settings:
    handler: src/functions/settings.put
    events:
      - http:
          path: /settings
          method: put
          cors: true

  get_settings:
    handler: src/functions/settings.get
    events:
      - http:
          path: /settings
          method: get
          cors: true

  get_quote:
    handler: src/functions/quote.get
    events:
      - http:
          path: /quote/{emotion}
          method: get
          cors: true

  authorisation:
    handler: src/functions/authorize.authorize
    events:
      - http:
          path: /authorize
          method: get
          cors: true

  siginin:
    handler: src/functions/sign_in.sign_in
    events:
      - http:
          path: /authorize
          method: POST
          cors: false

  account_exists:
    handler: src/functions/account.exists
    events:
      - http:
          path: /account/exists
          method: get
          cors: true

  token:
    handler: src/functions/token.get_token
    events:
      - http:
          path: /token
          method: post
          cors: true
