service: feeling-api

plugins:
  - serverless-offline-python
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-2

functions:
  app:
    handler: src/functions/app.app
    events:
      - http:
          path: /
          method: get
          cors: true

  authorisation:
    handler: src/functions/authorize.authorize
    events:
      - http:
          path: /authorize
          method: get
          cors: true

  siginin:
    handler: src/functions/SignIn.sign_in
    events:
    - http:
        path: /authorize
        method: POST
        cors: false





