service: feeling-api

plugins:
  - serverless-offline-python
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-2

functions:
  put_settings:
    handler: src/functions/settings.put
    events:
      - http:
          path: /settings
          method: put
          cors: true
  get_settings:
    handler: src/functions/settings.get
    events:
      - http:
          path: /settings
          method: get
          cors: true
  get_quote:
    handler: src/functions/quote.get
    events:
      - http:
          path: /quote/{emotion}
          method: get
          cors: true
